services:
  app:
    build:
      context: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    volumes:
      - .:/app
    links:
      - app
